"""index blogs.author

Revision ID: 87b6f5cc3af7
Revises: 598dd11d83eb
Create Date: 2026-10-02 11:35:38.728683

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '87b6f5cc3af7'
down_revision: str | Sequence[str] | None = '598dd11d83eb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blogs_author'), 'blogs', ['author'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogs_author'), table_name='blogs')
    # ### end Alembic commands ###
